config/routes.rb
Rails.application.routes.draw do
 
  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  
  devise_for:users,skip: [:passwords],controllers:{
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }
  
  devise_for:admin, skip: [:registrations, :passwords] ,controllers:{
    sessions: "admin/sessions"
  }
  
  resources :users, only:[:show, :edit, :update]
  
  resources :items, only:[:index, :show]
  
  resources :cart_items, only:[:index, :create, :update, :destroy] do
    collection do
      delete :destroy_all
    end
  end
  
  resources :orders, only:[:new, :index, :create, :show] do
    collection do
      get   :confirm
      patch :complete
    end
  end
  
  resources :genres, only:[:show]
  
  
  namespace :admin do
    
    root to: 'homes#top'
    
    resources :items
    
    resources :genres, only:[:create, :index, :edit, :update]
    
    resources :users, only:[:index, :show, :edit, :update]
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :user
    belongs_to :item
    
    def subtotal
      item.price * amount
    end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_one_attached :image
    
    has_many :cart_items
    belongs_to :genre
    
     def get_image
      (image.attached?) ? image : 'no_image.jpg'
     end
    
end

app/models/order.rb
class Order < ApplicationRecord
    has_many   :order_items
    has_many   :items, throuth: :order_item
    belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.all
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_items_path
      flash[:notice] = '新しい商品を登録しました'
    else
      render "new"
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
      flash[:notice] = '商品情報を編集しました'
    else
      render :"show"
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :image)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end


  
  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  def index
    @cart_items = current_user.cart_items
    @total = 0
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(amount: params[:cart_item][:amount].to_i)
    redirect_to cart_items_path
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_item_path
  end
  
  def destroy_all
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy_all
    redirect_to cart_item_path
  end
  
  def create
    @new_cart_item = current_user.cart_items.new(cart_item_params)
    if current_user.cart_items.find_by(item_id: @new_cart_item.item.id)
      @cart_item = current_user.cart_items.find_by(item_id: @new_cart_item.item.id)
      @cart_item.amount += @new_cart_item.amount
      @cart_item.save
    else
      @new_cart_item.save
    end
    redirect_to cart_items_path
  end
  
  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  
  def show
    @genre = Genre.find(params[:id])
    @items = @genre.item.where(is_active: true)
    @genre = Genre.all
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.all
    @genres = Genre.all
  end
  
  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
    @cart_item = CartItem.new
  end
  
  private
  def item_params
    params.require(:user).permit(:name,:price,:introduction)
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    @user = current_user
    @order = Order.new
  end
  
  def create
    @order = Order.new(order_params)
    cart_item = current_user.cart_items.all
    @order.save
    @order.user_id = current_user.id
      current_user.cart_items.each do |cart_item|
        @order_item = OrderItem.new
        @order_item.order_id = @order.id
        @order_item.item_id = cart_item.item_id
        @order_item.price = cart_item.item_id
        @order_item.amount = cart_item.amount
        @order_item.save
      end
      cart_item.destroy_all
      redirect_to complete_orders_path
  end
  
  def confirm
    @user = current_user
    @cart_items = CartItem.all
    @order = current_user.orders.new
    @order = Order.new(order_params)
    
    @total = 0
    @order.user_id = current_user.id
    if params[:order] == "0"
      @order.name = current_user.name
    end
  end
  
  def complete
  end
  
  def index
    @orders = Order.all
    @order = current_user.orders
  end
  
  def show
    @order = Order.find(params[:id])
    @order_items = @order.orderitems
    @user = current_user
  end
  
private
  def order_params
    params.require(:order).permit(:user_id, :name, :address, :pay_method)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :商品画像 %>
          <%= f.file_field :image, placeholder: "選択されていません", accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :商品名 %>
          <%= f.text_field :name, placeholder: "商品名" %>
        </div>
        <div class="form-group">
          <%= f.label :商品説明 %>
          <%= f.text_area :introduction, placeholder: "商品説明" %>
        </div>
        <div class="form-group">
          <%= f.label :ジャンル %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"} %>
        </div>
        <div class="form-group">
          <%= f.label :価格 %>
          ￥<%= f.text_field :price, placeholder: 1000 %>
        </div>
        <div class="form-submit-btn">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2>商品一覧</h2>
      <%= link_to "商品追加", new_admin_item_path, class: "btn btn-success" %>
      <table class="table">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>価格</th>
          <th>ジャンル</th>
          <th></th>
        </tr>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.name %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td><%= link_to "詳細", admin_item_path(item), class: "btn btn-primary" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2>新規登録</h2>
      <%= form_with model:@item, url: admin_items_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :商品画像 %>
          <%= f.file_field :image, placeholder: "選択されていません", accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :商品名 %>
          <%= f.text_field :name, placeholder: "商品名" %>
        </div>
        <div class="form-group">
          <%= f.label :商品説明 %>
          <%= f.text_area :introduction, placeholder: "商品説明" %>
        </div>
        <div class="form-group">
          <%= f.label :ジャンル %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"} %>
        </div>
        <div class="form-group">
          <%= f.label :価格 %>
          ￥<%= f.text_field :price, placeholder: 1000 %>
        </div>
        <div class="form-submit-btn">
          <%= f.submit "新規登録", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>商品詳細</h2>
    </div>
    <div class="col-md-8">
      <table class="table">
        <tr>
          <% if @item.image.attached? %>
            <%= image_tag @item.image, size: "250×250" %>
          <% else %>
            <%= image_tag 'no_image', size: "250×250" %>
          <% end %>
        </tr>
      </table>
    </div>
    <div class="col-md-6 offset-1">
      <table class="table">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>価格</th>
          <td>￥<%= @item.price %></td>
        </tr>
        <tr>
          <td><%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %></td>
          <td><%= link_to "一覧に戻る", admin_items_path, class: "btn btn-primary" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<h4>item list</h4>
<div class="item_container">
  <% @items.each do |item| %>
    <%= link_to item_path(item.id) do %>
      <%= image_tag item.get_image, size: '100×100' %>
    <% end %>
    <%= item.name %>
    <%= item.price %>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="item_box">
  <%= image_tag @item.get_image, size: "300×300" %>
  <%= @item.name %>
  <%= @item.introduction %>
  <%= @item.price %>
</div>
<div class="cart">
  <%= form_with model: @cart_item, url: cart_items_path, method: :post do |f| %>
    <% if user_signed_in? %>
      <%= f.hidden_field :item_id, :value => @item.id %>
      <%= f.select :amount, *[1..10] %>
      <%= f.submit "カートに入れる" %>
    <% else %>
      <%= link_to "会員登録が必要", new_user_registration_path %>
    <% end %>
  <% end %>
</div>