config/routes.rb
Rails.application.routes.draw do
 
  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  
  devise_for:users,skip: [:passwords],controllers:{
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }
  
  devise_for:admin, skip: [:registrations, :passwords] ,controllers:{
    sessions: "admin/sessions"
  }
  
  resources :users, only:[:show, :edit, :update]
  
  resources :items, only:[:index, :show]
  
  resources :cart_items, only:[:index, :create, :update, :destroy] do
    collection do
      delete :destroy_all
    end
  end
  
  resources :orders, only:[:new, :index, :create, :show] do
    collection do
      get   :confirm
      patch :complete
    end
  end
  
  resources :genres, only:[:show]
  
  
  namespace :admin do
    
    root to: 'homes#top'
    
    resources :items
    
    resources :genres, only:[:create, :index, :edit, :update]
    
    resources :users, only:[:index, :show, :edit, :update]
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :user
    belongs_to :item
    
    def subtotal
      item.price * amount
    end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_one_attached :image
    
    has_many :cart_items
    belongs_to :genre
    
     def get_image
      (image.attached?) ? image : 'no_image.jpg'
     end
    
end

app/models/order.rb
class Order < ApplicationRecord
    has_many   :order_items
    has_many   :items, throuth: :order_item
    belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  
  def show
    @genre = Genre.find(params[:id])
    @items = @genre.item.where(is_active: true)
    @genre = Genre.all
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.all
    @genres = Genre.all
  end
  
  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
    @cart_item = CartItem.new
  end
  
  private
  def item_params
    params.require(:user).permit(:name,:price,:introduction)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-secondary">
    <div class="container">
    <% if user_signed_in? %>
       <li class="nav-link">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-dark" %>
      </li>
      <li class="nav-link">
        <%= link_to "商品一覧", items_path, class: "nav-link text-dark" %>
      </li>
      <li class="nav-link">
        <%= link_to "ユーザ情報", user_path(current_user), class: "nav-link text-dark" %>
      </li>
      <li class="nav-link">
        <%= link_to "カート", cart_items_path, class: "nav-link text-dark" %>
      </li>
    <% elsif admin_signed_in? %>
      <li class="nav-link">
        <%= link_to "商品一覧", admin_items_path, class: "nav-link text-dark" %>
      </li>
      <li class="nav-link">
        <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link text-dark" %>
      </li>
      <li class="nav-link">
        <%= link_to "会員一覧", admin_users_path, class: "nav-link text-dark" %>
      </li>
      <li class="nav-link">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-dark" %>
      </li>
    <% else %>
      <li class="nav-link">
        <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-dark" %>
      </li>
      <li class="nav-link">
        <%= link_to "ログイン", new_user_session_path, class: "nav-link text-dark" %>
      </li>
    <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appnew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>